### ISSUE TITLE
PowerShell 6 PSReadLine-Beta

### ISSUE THREAD

**Issue by lgjmac** [chawyehsu/base16-concfg#2]
Hi, have you had a look at PSReadLine 2.0.0 
install-module -allowclobber -allowprerelease -force PSReadLine
I am running pwsh 6 and this version of PSReadLine doesn't seem to follow the same parameter commands:
CommandType     Name                                               Version    Source    
-----------     ----                                               -------    ------    
Function        PSConsoleHostReadLine                              2.0.0      PSReadLine
Cmdlet          Get-PSReadLineKeyHandler                           2.0.0      PSReadLine
Cmdlet          Get-PSReadLineOption                               2.0.0      PSReadLine
Cmdlet          Remove-PSReadLineKeyHandler                        2.0.0      PSReadLine
Cmdlet          Set-PSReadLineKeyHandler                           2.0.0      PSReadLine
Cmdlet          Set-PSReadLineOption                               2.0.0      PSReadLine

**Comment by chawyehsu** [comment]
It seems the new beta version of PSReadLine makes breaking changes on `Set-PSReadLineOption`:

https://github.com/lzybkr/PSReadLine/releases/tag/v2.0.0-beta1
```
Breaking changes:
* Requires PowerShell V5 or later and .Net 4.6.1
* Set-PSReadLineOption options have changed
  - To specify colors, use the new `-Color` parameter and pass a Hashtable
  - All other color options have been removed include `-ResetTokenColors`
  - To specify background colors, you must now use a VT escape sequence.
* Changing the end of the prompt to red may not work automatically anymore if
  your prompt is non-trivial. To fix, use `Set-PSReadLineOption -PromptText "> "`.
* Consistently use `PSReadLine` instead of `PSReadline` everywhere, APIs, cmdlets, files, etc.
* Building requires VS2017
```

I have no idea about it, since I don't use beta version of PSReadLine currently. What happens when you're using it.

**Comment by lgjmac** [comment]
Hey
Sorry for delay. Yeah basically it does make those breaking changes that's exactly right.
It is a better version of PSReadline though.
The colors in Windows Console are a mystery to me. 
How did you alter them?
It might be a quicker fix than that sounds though. Especially if we are all using ConEmu. Possibly just a script that reorders the colors in the conemu xml file especially if we are importing them using:
https://github.com/joonro/ConEmu-Color-Themes/blob/master/Install-ConEmuTheme.ps1
It is probably just an addition.
Do you have a map that maps the wrong conemu colortables to the correct ones? I could perhaps put something together in python or pwoershell
I think I had a look at your repo properly a while ago and couldn't work it out but I may not have had too much time.
L

**Comment by chawyehsu** [comment]
if you're using ConEmu/Cmder, there is nothing could be fixed with this repository, this is for those users who are using the pure PowerShell/cmd.exe console (specifically, the `conhost.exe`), and using the [concfg](https://github.com/lukesampson/concfg) application to modify theme.

ConEmu/Cmder has its own color/theme management system. (Settings->Features->Colors) Even if you change the color theme of Windows Console, that won't work correct if you didn't setup a theme in ConEmu/Cmder.

To do so, you could see my another base16 repository for ConEmu/Cmder - https://github.com/h404bi/base16-conemu. They are two different things.

But the PSReadline breaking changes affects both of this, especially this repository. I'll open a branch for the new version of PSReadline later.

**Comment by lgjmac** [comment]
Thank you.
I'll check out your other repository. I was sure I had it set up better than it is at the moment, and it may have been yours I used and then forgot about.
Sounds like it would be worth doing for the new PSReadline branch at some stage. It is pretty cool.
